const facultyDetail = [
    {
    "imgSrc":"../photos/DrOnaiza.png",
      "Name":"Dr. Onaiza Maqbool",
      "Designation": "Associate Professor, Chairperson",
      "Email": "onaiza@qau.edu.pk",
      "Phone": "+92-51-9064 2060",
      "ResearchInterests": ["Software reengineering","Software architecture recovery","Program understanding","Machine learning"],
      "Teachings": [{"degree":"M.Phill/PHD","courses":["Advanced Analysis of Algorithms","Knowledge Representation and Reasonin","Software Architectures","Data Mining","Machine Learning","Pattern Recognition","Software Evolution and Reengineering",
                    "Software Repositories Mining"]},{"degree":"Msc/BS","courses":["Introduction to Software Engineering","Artificial Intelligence"," Software Engineering","Software Engineering Practicum",
                    " Introduction to Computing Theory"," Analysis and Design for Software Systems"," Software Construction"," Theory of Automata"]}],
    "Publications": ["Jaweria Kanwal, Katsuro Inoue and Onaiza Maqbool, �Refactoring Patterns Study in Code Clones during Software Evolution�, International workshop on software clones � in conjunction with the International Conference on Software Analysis, Evolution and Re-engineering, to be held from Feb 21st-24th, 2017 (accepted for publication)",
                    "Rabeeh Ayaz Abbasi, Onaiza Maqbool, Mubashar Mushtaq, Naif R. Aljohani, Ali Daud, Jalal S. Alowibdi, Basit Shahzad, �Saving Lives Using Social Media: Analysis of the Role of Twitter for Personal Blood Donation Requests and Dissemination�, Telematics and Informatics (Elsevier-Netherlands) Available online 3 February 2017, ISSN 0736-5853, http://dx.doi.org/10.1016/j.tele.2017.01.010",
                    "M. Aslam Jarwar, Rabeeh Ayaz Abbasi, Mubashar Mushtaq, Onaiza Maqbool, Naif R. Aljohani, Ali Daud, Jalal S. Alowibdi,  J.R. Cano, S. Garc�a, Ilyoung Chong, �CommuniMents: A Framework for Detecting Community Based Sentiments for Events�,  International Journal on Semantic Web and Information Systems (IJSWIS) USA , 13(2), 2017.",
                    " Maryam Hamdani, Onaiza Maqbool, Jaweria Kanwal, �Supervised Learning for Orphan Adoption Problem in Software Architecture Recovery�, Malaysian Journal of Computer Science (Malaysia), 29(4):287-313, 2016",
                    "Rashid Naseem, Mustafa Bin Mat Deris, Onaiza Maqbool, Jing-peng Li, Sara Shahzad, Habib Shah, �Improved binary similarity measures for software modularization�, Frontiers of Information Technology & Electronic Engineering (China), (accepted for publication April 2016 � In press DOI: 10.1631/FITEE.1500373).",
                    "Aakash Ahmed, Claus Pahl, Fawad Khaliq, Onaiza Maqbool, Pooyan Jamshidi, �Exploiting patterns and tool support for reusable and automated change support for software architectures�, International Journal of Software Engineering (Eygpt), 9(1):35-58, January 2016",
                    "Jaweria Kanwal, Onaiza Maqbool, Rabeeh Ayaz Abbasi and Abdul Qudus Abbasi, �Network Analysis of Software Change History for Understanding Software Evolution�, In Proc. of the International Multi-topic Conference, Dec 2014.",
                    "Rashid Naseem, Bin Mat Deris and Onaiza Maqbool, �Software Modularization using Combination of Multiple Clustering�, In Proc. of the International Multi-topic Conference, Dec 2014",
                    "Farzana Gul and Onaiza Maqbool, �Structural Clone Detection with Hierarchical Clustering�, Intl. Conference on Modern Communication and Computing Technologies, February 2014",
                    "Imran Zahoor,  Web Application fact extractor (WAFE). In Proc. of the Intl. Conference on Digital Information Management, September 2013: 379-384",
                    "Rashid Naseem, Onaiza Maqbool, Siraj Muhammad, �Cooperative Software Clustering�, Journal of Systems and Software (USA), 86(8):2045-2062, August 2013",
                    "Faiza Siddique, Onaiza Maqbool, �Enhancing Comprehensibility of Software Clustering Results�, IET Software, 6(4):283-295,  August 2012",
                    "Siraj Muhammad, Onaiza Maqbool, Abdul Qudus Abbasi, 'Evaluating Relationship Categories for Clustering Object-Oriented Software Systems', IET Software, 6(3):260-274, June 2012 ",
                    "Jaweria Kanwal and Onaiza Maqbool, 'Bug Prioritization to Facilitate Bug Report Triage', Journal of Computer Science and Technology, 27(2):397-412, March 2012",
                    "Maryam Bibi and Onaiza Maqbool, 'Version Information Support for Software Architecture Recovery', In Proc. of the International Conference on Emerging Technologies, Septemher 2011",
                    "Faiza Siddique and Onaiza Maqbool, 'Analyzing Term Weighting Schemes for Labeling Software Clusters', In Proc. of the Conference on Software Maintenance and Re-engineering (CSMR), March 2011",
                    "Rashid Naseem, Onaiza Maqbool and Siraj Muhammad, Improved Similarity Measures For Software Clustering, In Proc. of the Conference on Software Maintenance and Re-engineering (CSMR), March 2011",
                    "Jaweria Kanwal, Onaiza Maqbool, Managing Open Bug Repositories through Bug Report Prioritization Using SVMs, In Proc. of the International Conference on Open-Source Systems and Technologies, December 2010",
                    "Jehangir Ashraf Awan, Onaiza Maqbool, 'Application of Artificial Neural Networks for Monsoon Rainfall Prediction', In Proc. of the International Conference on Emerging Technologies, October 2010",
                    "Mohammad Siraj, Onaiza Maqbool, Abdul Qudus Abbasi, Role of Relationships during Clustering of Object-Oriented Software Systems, In Proc. of the International Conference on Emerging Technologies, October 2010",
                    "Rashid Naseem, Onaiza Maqbool, An Improved Similarity Measure for Binary Features in Software Clustering, In Proc. of the International Conference on Computational Intelligence, Modelling and Simulation, September 2010",
                    "Imran Hassan, Onaiza Maqbool, Qaisar Ahsan, Usman Qayyum 'Cascading Neural Network with Adaboost for Face Detection', In Proc. of the International Conference on Applied Sciences and Technology, January 2010",
                    "Shafqat Ali, O. Maqbool, Monitoring Software Evolution using Multiple Types of Changes, In Proc. of the IEEE International Conference on Emerging Technologies, October 2009",
                    "M. Sarwar, O. Maqbool, The RSO Algorithm for Reducing Number of Set Operations in Association Rule Mining, Lecture Notes in Artificial Intelligence, 5139:460-468, October 2008.",
                    "M. A. Qureshi, O. Maqbool, 'The Complexity of Teaching Computability and Complexity', In Proc. of the International Conference on Teaching and Learning (ICTL), November, 2007.",
                    "O.Maqbool, H.A.Babri, 'Bayesian Learning for Software Architecture Recovery', In Proc. of the International Conference on Electrical Engineering, pp. 1-6, April 2007.",
                    "O.Maqbool, H.A.Babri, 'Hierarchical Clustering for Software Architecture Recovery', IEEE Transactions on Software Engineering, 33(11):759-780, November 2007",
                    "O.Maqbool, H.A.Babri, 'A Stability Analysis of Clustering Algorithms', In Proc. of the International Multi-topic Conference, pp. 314-319, December 2006.",
                    "O.Maqbool, H.A.Babri, 'Automated Software Clustering: An Insight using Cluster labels', Journal of Systems and Software, 79(11):1632-1648, November 2006",
                    "O.Maqbool, H.A.Babri, A. Karim and S.M. Sarwar, 'Metarule-Guided Association Rule Mining for Program Understanding', IEE Software, 152(6):281-296, December 2005",
                    "O.Maqbool, H.A.Babri, 'Interpreting Clustering Results through Cluster Labeling', In Proc. of the IEEE International Conference on Emerging Technologies, pp. 429-434, September 2005.",
                    "O.Maqbool, A. Karim, H.A.Babri and S.M. Sarwar, 'Reverse Engineering using Association Rules', In Proc. of the International Multi-topic Conference, pp. 389-395, December 2004.",
                    "O.Maqbool, H.A.Babri, 'The Weighted Combined Algorithm: A Linkage Algorithm for Software Clustering', In Proc. of the Conference on Software Maintenance and Re-engineering (CSMR), pp. 15-24, March 2004.",
                    "M.Saeed, O.Maqbool, H.A.Babri, S.M. Sarwar and S.Z. Hassan, 'Software Clustering Techniques and the Use of the Combined Algorithm', In Proc. of the Conference on Software Maintenance and Re-engineering (CSMR), pp. 301-306, March 2003."],
                    "Conference":["UnAvailabe"],
                    "Workshop":["UnAvailabe"],
                    "Thesis":["UnAvailabe"],
                    "Projects":["UnAvailabe"],
                    "Activities":["UnAvailabe"]

    },
    {
        "imgSrc": "../photos/DrKhalid.png",
        "Name": "Dr. Khalid Saleem",
        "Designation": "Assistant Professor",
        "ResearchInterests": ["Database Systems", "Information Systems","Distributed Systems","Data Warehousing/Mining"],
        "Email": "ksaleem@qau.edu.pk",
        "Phone": "+92-51-9064 2061",
        "ResearchInterests": ["Information Systems - Database Systems", "Distributed Database Systems"," Data Warehousing","e-Government","Data Analytics - Data Mining (Open Data, Big Data and Scientific Data)"," Data for Development (D4D)", "Natural Language Processing (URDU)","Computing - Scientific, Steganography", "Encryption, Mobile, Green"],
        "Teachings":[{"degree":"Phd","courses":["sCS-863: Metadata Model Management","CS-823: Data Warehousing"]},{"degree":"M.Phill","courses":["CS-772: Data Mining","CS-751: Distributed Systems (Database)","CS-652: Advance Analysis of Algorithms","CS-702: Advance Operating Systems","CS-663: Knowledge Representation and Reasoning"]},{"degree":"MSIST","courses":["IST-652: Intelligent Information Systems","IST-672: e-Government","IST-785: Selected Topics in IST (Research Methods)"]},{"degree":"M.Sc.","courses":["CS-303: Rapid Application Development","CS-353: Database Design","CS-481: Mobile Computing Systems","CS-452: Analysis and Design of Algorithms","CS-351: Computer Architecture","CS-431: Information Systems"]},{"degree":"BSCS","courses":["CS-225: Database Systems","CS-324: Web Application Developmen","CS-424: Mobile Application Development"]}],
        "Conference":["UnAvailabe"],
        "Publications":["Unavailable"],
        "Workshop":["UnAvailabe"],
        "Thesis":["UnAvailabe"],
        "Projects":["UnAvailabe"],
        "Activities":["UnAvailabe"]
    },
    {
        "imgSrc": "../photos/photo.png",
        "Name": "Dr. Shuaib Karim",
        "Designation": "Assistant Professor",
        "ResearchInterests": ["Usability / Accessibility of Interactive Systems","Web Engineering","Applied aspects of ontologies"],
        "Email": "skarim@qau.edu.pk",
        "Phone": "+92-51-9064 2055",
        "Teachings":["Unavailable"],
        "Publications":["Unavailable"],
        "Conference":["UnAvailabe"],
        "Workshop":["UnAvailabe"],
        "Thesis":["UnAvailabe"],
        "Projects":["UnAvailabe"],
        "Activities":["UnAvailabe"]
    },
    {
        "imgSrc": "../photos/DrRabeeh.png",
        "Name": "Dr. Rabeeh Ayaz Abbasi",
        "Designation": "Assistant Professor",
        "ResearchInterests": ["Social Media Analytics","Social Network Analysis","Machine Learning"],
        "Email": "rabbasi@qau.edu.pk",
        "Phone": "+92-51-9064 2050",
        "Teachings":["UnAvailable"],
        "Publications":["Unavailable"],
        "Conference":["UnAvailabe"],
        "Workshop":["UnAvailabe"],
        "Thesis":["UnAvailabe"],
        "Projects":["UnAvailabe"],
        "Activities":["UnAvailabe"]
    },
    {
        "imgSrc": "../photos/DrGhazanfar.png",
        "Name": "Dr. Ghazanfar Farooq",
        "Designation": "Assistant Professor",
        "ResearchInterests": ["Agents (Virtual Agents)","Modeling and Simulation"],
        "Email": "ghazanfar@qau.edu.pk",
        "Phone": "+92-51-9064 2058",
         "Teachings":["UnAvailable"],
        "Publications":["Unavailable"],
        "Conference":["UnAvailabe"],
        "Workshop":["UnAvailabe"],
        "Thesis":["UnAvailabe"],
        "Projects":["UnAvailabe"],
        "Activities":["UnAvailabe"]
    },
    {
        "imgSrc": "../photos/DrSindhu.png",
        "Name": "Dr. Muddassar Azam Sindhu",
        "Designation": "Assistant Professor",
        "ResearchInterests": ["Software Testing","Model Mining,Formal Methods"],
        "Email": "masindhu@qau.edu.pk",
        "Phone": "+92-51-9064 2066",
         "Teachings":["UnAvailable"],
        "Publications":["Unavailable"],
        "Conference":["UnAvailabe"],
        "Workshop":["UnAvailabe"],
        "Thesis":["UnAvailabe"],
        "Projects":["UnAvailabe"],
        "Activities":["UnAvailabe"]
    },
    {
        "imgSrc": "../photos/DrKhattak.png",
        "Name": "Dr. Akmal Saeed Khattak",
        "Designation": "Assistant Professor",
        "ResearchInterests": ["Information Retrieval","Machine Learning","Text Mining","Natural Language Processing"],
        "Email": "akhattak@qau.edu.pk",
        "Phone": "+92-51-9064 2161",
        
        "Teachings":["UnAvailable"],
        "Publications":["Unavailable"],
        "Conference":["UnAvailabe"],
        "Workshop":["UnAvailabe"],
        "Thesis":["UnAvailabe"],
        "Projects":["UnAvailabe"],
        "Activities":["UnAvailabe"]
    },
    {
        "imgSrc": "../photos/DrUmer.png",
        "Name": "Dr. Umer Rasheed",
        "Designation": "Assistant Professor",
        "ResearchInterests": ["Multimedia Information Retrieval","Human Aspects of Computing"],
        "Email": "umerrashid@qau.edu.pk",
        "Phone": "+92-51-9064 2012",
        "Teachings":["UnAvailable"],
        "Publications":["Unavailable"],
        "Conference":["UnAvailabe"],
        "Workshop":["UnAvailabe"],
        "Thesis":["UnAvailabe"],
        "Projects":["UnAvailabe"],
        "Activities":["UnAvailabe"]
    },
    {
        "imgSrc": "../photos/MamMemoona.png",
        "Name": "Memoona Afsheen Malik",
        "Designation": "Lecturer",
        "ResearchInterests": ["Problem Solving and Programming","Data Structures and Algorithms"],
        "Email": "memoona@qau.edu.pk",
        "Phone": "+92-51-9064 2064",
        "Teachings":["UnAvailable"],
        "Publications":["Unavailable"],
        "Conference":["UnAvailabe"],
        "Workshop":["UnAvailabe"],
        "Thesis":["UnAvailabe"],
        "Projects":["UnAvailabe"],
        "Activities":["UnAvailabe"]
    },
    {
        "imgSrc": "../photos/MamIfrah.png",
        "Name": "Ifrah Farrukh Khan",
        "Designation": "Lecturer",
        "ResearchInterests": ["Database Systems","Networking"],
        "Email": "ifrahkhan@qau.edu.pk",
        "Phone": "+92-51-9064 2005",
         "Teachings":["UnAvailable"],
        "Publications":["Unavailable"],
        "Conference":["UnAvailabe"],
        "Workshop":["UnAvailabe"],
        "Thesis":["UnAvailabe"],
        "Projects":["UnAvailabe"],
        "Activities":["UnAvailabe"]
    },
    {
        "imgSrc": "../photos/SirNaqi.png",
        "Name": "S. M. Naqi",
        "Designation": "Lecturer",
        "ResearchInterests": ["Medical Imaging","Machine Learning","Image Segmentation and Classification"],
        "Email": "smnaqi@qau.edu.pk",
        "Phone": "+92-51-9064 2013",
        "Teachings":["UnAvailable"],
        "Publications":["Unavailable"],
        "Conference":["UnAvailabe"],
        "Workshop":["UnAvailabe"],
        "Thesis":["UnAvailabe"],
        "Projects":["UnAvailabe"],
        "Activities":["UnAvailabe"]
    }
  ]

export default facultyDetail;